<?php

namespace Database\Seeders;

use App\Models\Permission;

// certificate_issues
$manageCertificateIssues = Permission::create(['name' => 'manage_certificate_issues', 'display_name' => ['ar'  =>  'إدارة الشهائد',    'en'    =>  'Manage Certificates'], 'route' => 'company_certificates', 'module' => 'company_certificates', 'as' => 'company_certificates.index', 'icon' => 'fas fas fa-newspaper', 'parent' => '0', 'parent_original' => '0', 'sidebar_link' => '1', 'appear' => '1', 'ordering' => '50',]);
$manageCertificateIssues->parent_show = $manageCertificateIssues->id;
$manageCertificateIssues->save();
$showCertificateIssues      =  Permission::create(['name'  => 'show_certificate_issues', 'display_name'       =>  ['ar'   =>  'الشهائد',               'en'    =>  'Certificates'], 'route' => 'company_certificates', 'module' => 'company_certificates', 'as' => 'company_certificates.index', 'icon' => 'fas fas fa-newspaper', 'parent' => $manageCertificateIssues->id, 'parent_original' => $manageCertificateIssues->id, 'parent_show' => $manageCertificateIssues->id, 'sidebar_link' => '1', 'appear' => '1']);
$createCertificateIssues    =  Permission::create(['name'  => 'create_certificate_issues', 'display_name'     =>  ['ar'   =>  'إنشاء شهادة',           'en'    =>  'Create new Certificate'], 'route' => 'company_certificates', 'module' => 'company_certificates', 'as' => 'company_certificates.create', 'icon' => null, 'parent' => $manageCertificateIssues->id, 'parent_original' => $manageCertificateIssues->id, 'parent_show' => $manageCertificateIssues->id, 'sidebar_link' => '1', 'appear' => '0']);
$displayCertificateIssues   =  Permission::create(['name' => 'display_certificate_issues', 'display_name'    =>  ['ar'   =>  'عرض شهادة',              'en'    =>  'Display Certificate'], 'route' => 'company_certificates', 'module' => 'company_certificates', 'as' => 'company_certificates.show', 'icon' => null, 'parent' => $manageCertificateIssues->id, 'parent_original' => $manageCertificateIssues->id, 'parent_show' => $manageCertificateIssues->id, 'sidebar_link' => '0', 'appear' => '0']);
$updateCertificateIssues    =  Permission::create(['name' => 'update_certificate_issues', 'display_name'     =>  ['ar'   =>  'تعديل شهادة',            'en'    =>  'Edit Certificate'], 'route' => 'company_certificates', 'module' => 'company_certificates', 'as' => 'company_certificates.edit', 'icon' => null, 'parent' => $manageCertificateIssues->id, 'parent_original' => $manageCertificateIssues->id, 'parent_show' => $manageCertificateIssues->id, 'sidebar_link' => '0', 'appear' => '0']);
$deleteCertificateIssues    =  Permission::create(['name'  => 'delete_certificate_issues', 'display_name'     =>  ['ar'   =>  'حذف شهادة',              'en'    =>  'Delete Certificate'], 'route' => 'company_certificates', 'module' => 'company_certificates', 'as' => 'company_certificates.destroy', 'icon' => null, 'parent' => $manageCertificateIssues->id, 'parent_original' => $manageCertificateIssues->id, 'parent_show' => $manageCertificateIssues->id, 'sidebar_link' => '0', 'appear' => '0']);
