<?php

namespace Database\Seeders;

use App\Models\Permission;

// Certificate Requests
$manageCertificateRequests = Permission::create(['name' => 'manage_certificate_requests', 'display_name' => ['ar'  =>  'إدارة طلبات الشهائد ',    'en'    =>  'Manage Certificate Requests'], 'route' => 'certificate_requests', 'module' => 'certificate_requests', 'as' => 'certificates.index', 'icon' => 'fas fas fa-newspaper', 'parent' => '0', 'parent_original' => '0', 'sidebar_link' => '1', 'appear' => '1', 'ordering' => '50',]);
$manageCertificateRequests->parent_show = $manageCertificateRequests->id;
$manageCertificateRequests->save();
$showCertificateReguests      =  Permission::create(['name'  => 'show_certificate_requests', 'display_name'       =>  ['ar'   =>  'طلبات الشهائد',               'en'    =>  'Certificates Requests'], 'route' => 'certificate_requests', 'module' => 'certificate_requests', 'as' => 'certificates.index', 'icon' => 'fas fas fa-newspaper', 'parent' => $manageCertificateRequests->id, 'parent_original' => $manageCertificateRequests->id, 'parent_show' => $manageCertificateRequests->id, 'sidebar_link' => '1', 'appear' => '1']);
$createCertificateReguests    =  Permission::create(['name'  => 'create_certificate_requests', 'display_name'     =>  ['ar'   =>  'إنشاء طلبات الشهائد',           'en'    =>  'Create new Certificate Request'], 'route' => 'certificate_requests', 'module' => 'certificate_requests', 'as' => 'certificates.create', 'icon' => null, 'parent' => $manageCertificateRequests->id, 'parent_original' => $manageCertificateRequests->id, 'parent_show' => $manageCertificateRequests->id, 'sidebar_link' => '1', 'appear' => '0']);
$displayCertificateReguests   =  Permission::create(['name' => 'display_certificate_requests', 'display_name'    =>  ['ar'   =>  'عرض طلبات الشهائد',              'en'    =>  'Display Certificate Request'], 'route' => 'certificate_requests', 'module' => 'certificate_requests', 'as' => 'certificates.show', 'icon' => null, 'parent' => $manageCertificateRequests->id, 'parent_original' => $manageCertificateRequests->id, 'parent_show' => $manageCertificateRequests->id, 'sidebar_link' => '0', 'appear' => '0']);
$updateCertificateReguests    =  Permission::create(['name' => 'update_certificate_requests', 'display_name'     =>  ['ar'   =>  'تعديل طلبات الشهائد',            'en'    =>  'Edit Certificate Request'], 'route' => 'certificate_requests', 'module' => 'certificate_requests', 'as' => 'certificates.edit', 'icon' => null, 'parent' => $manageCertificateRequests->id, 'parent_original' => $manageCertificateRequests->id, 'parent_show' => $manageCertificateRequests->id, 'sidebar_link' => '0', 'appear' => '0']);
$deleteCertificateReguests    =  Permission::create(['name'  => 'delete_certificate_requests', 'display_name'     =>  ['ar'   =>  'حذف طلبات الشهائد',              'en'    =>  'Delete Certificate Request'], 'route' => 'certificate_requests', 'module' => 'certificate_requests', 'as' => 'certificates.destroy', 'icon' => null, 'parent' => $manageCertificateRequests->id, 'parent_original' => $manageCertificateRequests->id, 'parent_show' => $manageCertificateRequests->id, 'sidebar_link' => '0', 'appear' => '0']);
